blueprint:
  name: Controllo Umidità con Ventola (Corretto)
  description: Gestisce la ventola del bagno in base al passaggio di umidità relativa.
  domain: automation
  input:
    umidita:
      name: Sensore Umidità Locale
      selector:
        entity:
          domain: sensor
          multiple: false
    umidita_riferimento:
      name: Sensore Umidità Base
      selector:
        entity:
          domain: sensor
          multiple: false
    percentuale_a:
      name: Percentuale A
      selector:
        number:
          min: 0
          max: 100
          step: 1.0
          unit_of_measurement: '%'
          mode: slider
    percentuale_b:
      name: Percentuale B
      selector:
        number:
          min: 0
          max: 100
          step: 1.0
          unit_of_measurement: '%'
          mode: slider
    switch_ventola:
      name: Switch Ventola
      selector:
        entity:
          domain: switch
          multiple: false
    sensore_booleano:
      name: Sensore Booleano
      selector:
        entity:
          domain: input_boolean
    minuti_timer:
      name: Minuti Timer
      description: Numero di minuti per cui la ventola rimarrà accesa se attivata manualmente.
      selector:
        number:
          min: 1
          max: 60
          step: 1.0
          unit_of_measurement: 'minuti'
          mode: slider

  trigger:
    - platform: state
      entity_id: !input umidita 
    - platform: state
      entity_id: !input switch_ventola 
      to: 'on'

  action:
